[alias]
# Quick check all
c = "check --workspace --all-targets"
# Quick test all
t = "test --workspace"
# Format check
fc = "fmt --all -- --check"
# Clippy all
cl = "clippy --workspace --all-targets"
# Run all checks (format, clippy, test)
all = "xtask all"

[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

[target.x86_64-apple-darwin]
linker = "clang"
