[package]
name = "warcraftlogs-fetcher"
version.workspace = true
edition.workspace = true

[dependencies]
scraper = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
regex-lite = { workspace = true }
headless_chrome = { workspace = true }
