[package]
name = "warcraftlogs-fetcher"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true }
scraper = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
regex-lite = { workspace = true }
